### ISSUE TITLE
Data issue

### ISSUE THREAD

**Issue by mucun1988** [AlexGrinch/ro_sgns#1]
In enwik_experiments.ipynb, the data data/enwik/enwik9.txt seems to be needed. Could you please provide this data in the repo?

Thanks,
Matt

**Comment by AlexGrinch** [comment]
Hi Matt,

We have taken English Wikipedia from enwik9.zip
<http://mattmahoney.net/dc/enwik9.zip>. To run the experiments you should
also clean the data from html marks and other symbols which are not useful.
Please, see the attached Perl script we used to clean the data (actually it
is taken from Matt Mahoney site too with minor changes).

Best,
Aleksey

**Comment by mucun1988** [comment]
Dear Aleksey


Many thanks for the response!

May I know where the Perl script is? I did not find any file attached. Is it in the repo? 


Best,
Matt

**Comment by AlexGrinch** [comment]
[main_.txt](https://github.com/AlexGrinch/ro_sgns/files/1534389/main_.txt)

Oh, excuse me, I did not notice that it was comment on Github and answered by email with the attachment to it. Please see the attached script (I had to rename it to .txt as Github did not allow me to upload .pl file).

Best,
Aleksey

**Comment by mucun1988** [comment]
Great! Will have a try. Thanks for the response and great work!

Best,
Matt
