### ISSUE TITLE
SGD-SGNS

### ISSUE THREAD

**Issue by mucun1988** [AlexGrinch/ro_sgns#2]
Dear Alex

Is the method SGD-SGNS included in the repo?

If not, may I know which implementation you used for experiment?

Thanks,
Matt

**Comment by AlexGrinch** [comment]
Hi Matt,

We used gensim implementation of word2vec (https://radimrehurek.com/gensim/models/word2vec.html)

Best,
Aleksey

**Comment by mucun1988** [comment]
Great! will take a look!

Thanks,
Matt

**Comment by mucun1988** [comment]
Hi Alex

Is it possible to find out the code using word2vec? Is the default setting in gensim being used?

Thanks,
Matt

**Comment by AlexGrinch** [comment]
Hi Matt

Please, take a look at this code. As far as I remember, we only played with the number of iterations (iter) and looked at correlations for different numbers of iterations, and it converged to the values listed in the paper.

import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s',\
    level=logging.INFO)

"""Set values for various parameters"""
num_features = 100 # Word vector dimensionality                      
min_word_count = 100 # Minimum word count                        
num_workers = 4 # Number of threads to run in parallel
context = 5 # Context window size                                                                                    
downsampling = 1e-3 # Downsample setting for frequent words
negative = 5 # Negative sampling parameter
iter = 20 # Number of iterations

from gensim.models import word2vec
model = word2vec.Word2Vec(sentences, 
workers=num_workers, 
size=num_features, 
min_count=min_word_count,
window=context, 
sample=downsampling,
negative=negative,
iter=iter)

"""If you don't plan to train the model any further, calling 
init_sims will make the model much more memory-efficient."""
model.init_sims(replace=True)

"""It can be helpful to create a meaningful model name and 
save the model for later use. You can load it later using Word2Vec.load()"""
model_name = "100features_100minwords_5context"
model.save(model_name)

Best,
Aleksey

**Comment by mucun1988** [comment]
Wow! That's really helpful, as I am not that familiar with gensim...

Thank you so much!

Sincerely,
Matt
